# Generated by Django 3.2.13 on 2022-06-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customeraddress_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
    ]
