# Generated by Django 3.2.13 on 2022-07-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220611_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='complement',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento'),
        ),
    ]
