# Generated by Django 3.2.13 on 2022-06-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome produto')),
                ('short_description', models.TextField(max_length=255, verbose_name='Descrição curta')),
                ('long_description', models.TextField(verbose_name='Descrição longa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/', verbose_name='Imagem')),
                ('slug', models.SlugField(unique=True)),
                ('mkt_price', models.FloatField(verbose_name='Preço de exibição')),
                ('mkt_discount_price', models.FloatField(default=0, verbose_name='Preço promocional de exibição')),
                ('type_product', models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1, verbose_name='Tipo de produto')),
            ],
        ),
    ]
