# Generated by Django 3.2.13 on 2022-06-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mkt_discount_price',
            new_name='mkt_price_discount',
        ),
    ]
