# Generated by Django 3.2.13 on 2022-06-09 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_mkt_discount_price_product_mkt_price_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('promotional_price', models.FloatField(default=0, verbose_name='Preço promocional')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Modelo')),
            ],
        ),
    ]
