# Generated by Django 3.2.13 on 2022-06-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_discount',
            new_name='promotional_price',
        ),
    ]
