# Generated by Django 3.2.13 on 2022-08-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_price_discount_orderitem_promotional_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qtd_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
