# Generated by Django 3.2.13 on 2022-08-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_qtd_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qtd_total',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
