# Generated by Django 3.2.13 on 2022-08-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220803_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qtd_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd Total'),
            preserve_default=False,
        ),
    ]
