# Generated by Django 3.2.13 on 2022-08-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_qtd_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qtd_total',
            field=models.PositiveIntegerField(verbose_name='Qtd Itens'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(verbose_name='Valor total do Pedido'),
        ),
    ]
